/* Field definitions mirroring scene_reports_app's schema field-for-field,
   so an exported capture maps directly onto the desktop import bridge.
   Field "type": text | date | time | textarea | select */

const COMPANY_OPTIONS = ["BCPS", "Ukhozi"];

const CHOICES = {
  DEVICE_ON_OFF_STANDBY: ["On", "Off", "Standby", "Sleep"],
  HDD_TYPE: ["N/A", "NVMe", "SATA", "SATA SSD", "SSD", "USB", "Onboard", "Apple HDD", "Apple NVMe", "Ext HDD"],
  EXTENT_OF_ACQUISITION_GENERAL: ["N/A", "Whole Disk", "Partition", "Folders", "Files", "Whole Disk (Logical)"],
  EXTENT_OF_ACQUISITION_STORAGE: ["N/A", "Whole Disk", "Partition", "Folders", "Files"],
  METHOD_USED: ["N/A", "Fast Block", "Software Block", "Live", "TD2/3/TX", "Other"],
  NOTES_ON_ACQUISITION: ["Success", "Verified", "Failed", "Errors"],
  PROGRAM_OPTIONS_GENERAL: ["N/A", "Paladin", "Caine", "Kali Linux", "Macquisition (Cellebrite Digital Collector)", "FTK Imager", "EnCase", "GetData", "LLIMAGER"],
  PROGRAM_OPTIONS_STORAGE: ["N/A", "Paladin", "Caine", "Kali Linux", "Macquisition (Cellebrite Digital Collector)", "FTK Imager", "EnCase", "GetData"],
  TYPE_OF_MOBILE_DEVICE: ["Phone", "Tablet", "Watch"],
  MOBILE_ON_OFF: ["On", "Off"],
  MOBILE_ACCESSORIES: ["Charger", "Case", "Data Cable", "None"],
  MOBILE_CONDITION: ["New", "Used", "Screen Damaged"],
  MOBILE_ACQ_PROGRAM: ["Cellebrite", "MOBILEdit", "Oxygen", "SPF", "XRY", "N/A"],
  MOBILE_EXTENT: ["Physical", "Logical", "File System", "APK Downgrade", "MOBILEdit Screenshots", "WhatsApp Extraction", "N/A"],
  DESTINATION_TYPE: ["SATA", "USB"],
  SIM_CARD_EXTRACTION: ["Yes", "No", "N/A"],
  MEMORY_CARD_TYPE: ["SD", "Mini SD", "Micro SD", "N/A"],
  MEMORY_CARD_ACQ_PROGRAM: ["FTK Imager", "Cellebrite", "N/A"],
  TYPE_OF_EMAIL_ACCOUNT: ["Exchange", "Mimecast", "Office 365"],
};

const CASE_FIELDS = [
  { name: "dfl_ref_nr", label: "DFL Ref Nr", type: "text" },
  { name: "bcps_case_nr", label: "Case Nr", type: "text", hint: 'Shown as "BCPS Case Nr" or "Ukhozi Case Nr" depending on Company' },
  { name: "case_name", label: "Case Name", type: "text" },
  { name: "client_name", label: "Client Name", type: "text" },
  { name: "client_representative", label: "Client Representative", type: "text" },
  { name: "client_address", label: "Client Address", type: "textarea" },
  { name: "client_tel", label: "Client Tel", type: "text" },
];

const SCENE_FIELDS = [
  { name: "premises_address", label: "Premises Address", type: "textarea" },
  { name: "office_nr", label: "Office Nr", type: "text" },
  { name: "location", label: "Location of Device", type: "text" },
  { name: "person_found", label: "Person Found @ Device", type: "text" },
  { name: "owner_custodian", label: "Owner/Authorized User/Custodian", type: "text" },
  { name: "notes", label: "Notes", type: "textarea" },
];

const VERIFICATION_FIELDS = [
  { name: "source_device_imaged_by", label: "Source Device Imaged By", type: "text", hint: "Initials & Surname" },
  { name: "source_device_imaged_by_signature", label: "Signature — Source Device Imaged By", type: "signature" },
  { name: "hashes_verified_by", label: "Hashes Verified By", type: "text", hint: "Initials & Surname" },
  { name: "person_present", label: "Person Present During Acquisition", type: "text" },
  { name: "person_present_date", label: "Date", type: "date" },
  { name: "person_present_signature", label: "Signature — Person Present", type: "signature" },
  { name: "person_inspecting", label: "Person Inspecting (post-acquisition)", type: "text" },
  { name: "person_inspecting_date", label: "Date", type: "date" },
  { name: "person_inspecting_signature", label: "Signature — Person Inspecting", type: "signature" },
];

const NOTES_FIELD = [{ name: "additional_scene_notes", label: "Additional Scene Notes", type: "textarea" }];

const REPORT_CONFIG = {
  general_image: {
    label: "General Image",
    evidenceHint: "e.g. DFL139_XOLANI_DHLAMINI_LPT1",
    sections: [
      {
        title: "Device Details",
        fields: [
          { name: "type_of_device", label: "Type of Device", type: "text", hint: "Laptop, Desktop, etc" },
          { name: "type_of_server", label: "Type of Server", type: "text", hint: "Windows, Mail, Linux, etc" },
          { name: "was_device_on_off", label: "Was Device On/Off", type: "select", options: CHOICES.DEVICE_ON_OFF_STANDBY },
          { name: "manufacturer", label: "Manufacturer", type: "text", hint: "Dell, HP, etc" },
          { name: "model_nr", label: "Model Nr", type: "text" },
          { name: "serial_nr", label: "Serial Nr", type: "text" },
          { name: "bios_date", label: "BIOS Date", type: "date" },
          { name: "bios_time", label: "BIOS Time", type: "time" },
          { name: "actual_date", label: "Actual Date", type: "date" },
          { name: "actual_time", label: "Actual Time", type: "time" },
          { name: "user_name", label: "User Name", type: "text" },
          { name: "user_password", label: "Password", type: "text" },
        ],
      },
      {
        title: "Source Disks",
        fields: [
          { name: "source1_hdd_type", label: "Source 1 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "source1_hdd_manufacturer", label: "Source 1 Manufacturer", type: "text" },
          { name: "source1_size", label: "Source 1 Size", type: "text", hint: "GB / TB" },
          { name: "source1_model_no", label: "Source 1 Model Nr", type: "text" },
          { name: "source1_serial_nr", label: "Source 1 Serial Nr", type: "text" },
          { name: "source2_hdd_type", label: "Source 2 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "source2_hdd_manufacturer", label: "Source 2 Manufacturer", type: "text" },
          { name: "source2_size", label: "Source 2 Size", type: "text", hint: "GB / TB" },
          { name: "source2_model_no", label: "Source 2 Model Nr", type: "text" },
          { name: "source2_serial_nr", label: "Source 2 Serial Nr", type: "text" },
        ],
      },
      {
        title: "Target (Forensic) Disks",
        fields: [
          { name: "target1_hdd_type", label: "Target 1 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "target1_hdd_manufacturer", label: "Target 1 Manufacturer", type: "text" },
          { name: "target1_size", label: "Target 1 Size", type: "text", hint: "GB / TB" },
          { name: "target1_model_no", label: "Target 1 Model Nr", type: "text" },
          { name: "target1_serial_nr", label: "Target 1 Serial Nr", type: "text" },
          { name: "target2_hdd_type", label: "Target 2 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "target2_hdd_manufacturer", label: "Target 2 Manufacturer", type: "text" },
          { name: "target2_size", label: "Target 2 Size", type: "text", hint: "GB / TB" },
          { name: "target2_model_no", label: "Target 2 Model Nr", type: "text" },
          { name: "target2_serial_nr", label: "Target 2 Serial Nr", type: "text" },
        ],
      },
      {
        title: "Acquisition Information (fill in later if not yet known)",
        fields: [
          { name: "source_device_description", label: "Source Device Description", type: "textarea" },
          { name: "acquisition_notes", label: "Acquisition Notes", type: "textarea" },
          { name: "acquisition_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "acquisition_start_time", label: "Start Time", type: "time" },
          { name: "acquisition_end_date", label: "Acquisition End Date", type: "date" },
          { name: "acquisition_end_time", label: "End Time", type: "time" },
          { name: "extent_of_acquisition", label: "Extent of Acquisition", type: "select", options: CHOICES.EXTENT_OF_ACQUISITION_GENERAL },
          { name: "method_used", label: "Method Used", type: "select", options: CHOICES.METHOD_USED },
          { name: "md5_hash_1", label: "MD5 Hash 1", type: "text" },
          { name: "sha1_hash_1", label: "SHA1 Hash 1", type: "text" },
          { name: "md5_hash_2", label: "MD5 Hash 2", type: "text" },
          { name: "sha1_hash_2", label: "SHA1 Hash 2", type: "text" },
          { name: "notes_on_acquisition", label: "Notes on Acquisition", type: "select", options: CHOICES.NOTES_ON_ACQUISITION },
          { name: "bitlocker_encryption_key", label: "Bitlocker/Encryption Key", type: "text" },
          { name: "imager_version", label: "Imager Version", type: "select", options: CHOICES.PROGRAM_OPTIONS_GENERAL },
          { name: "live_distro", label: "Live Distro", type: "select", options: CHOICES.PROGRAM_OPTIONS_GENERAL },
          { name: "other_specify", label: "Other Specify", type: "text" },
        ],
      },
      { title: "Verification", fields: VERIFICATION_FIELDS },
      { title: "Additional Scene Notes", fields: NOTES_FIELD },
    ],
  },

  mobile: {
    label: "Mobile",
    evidenceHint: "e.g. DFL139_XOLANI_DHLAMINI_MOB1",
    sections: [
      {
        title: "Device Details",
        fields: [
          { name: "type_of_mobile_device", label: "Type of Mobile Device", type: "select", options: CHOICES.TYPE_OF_MOBILE_DEVICE },
          { name: "manufacturer", label: "Manufacturer", type: "text", hint: "Huawei, Samsung, etc" },
          { name: "model_nr", label: "Model Nr", type: "text", hint: "P9, S6, etc" },
          { name: "imei_nr", label: "IMEI Nr", type: "text", hint: "*#06#" },
          { name: "sim_card_pin", label: "SIM Card PIN Nr", type: "text" },
          { name: "sec_code_password", label: "Sec Code / Password", type: "text" },
          { name: "service_provider", label: "Service Provider", type: "text" },
          { name: "sim_card_serial_nr", label: "SIM Card Serial Nr", type: "text" },
          { name: "mobile_phone_nr", label: "Mobile Phone Nr", type: "text" },
          { name: "itunes_icloud_username", label: "iTunes/Cloud Username", type: "text" },
          { name: "itunes_icloud_password", label: "iTunes/Cloud Password", type: "text" },
          { name: "mobile_date", label: "Mobile Date", type: "date" },
          { name: "mobile_time", label: "Mobile Time", type: "time" },
          { name: "actual_date", label: "Actual Date", type: "date" },
          { name: "actual_time", label: "Actual Time", type: "time" },
          { name: "mobile_on_off", label: "Mobile On/Off", type: "select", options: CHOICES.MOBILE_ON_OFF },
          { name: "device_notes", label: "Notes", type: "text" },
          { name: "mobile_device_accessories", label: "Mobile Device Accessories", type: "select", options: CHOICES.MOBILE_ACCESSORIES },
          { name: "condition_of_mobile_device", label: "Condition of Mobile Device", type: "select", options: CHOICES.MOBILE_CONDITION },
        ],
      },
      {
        title: "Acquisition Programs & Methodology",
        fields: [
          { name: "acquisition_program_1", label: "Program 1", type: "select", options: CHOICES.MOBILE_ACQ_PROGRAM },
          { name: "extent_of_acquisition_1", label: "Extent of Acquisition 1", type: "select", options: CHOICES.MOBILE_EXTENT },
          { name: "acquisition_program_2", label: "Program 2", type: "select", options: CHOICES.MOBILE_ACQ_PROGRAM },
          { name: "extent_of_acquisition_2", label: "Extent of Acquisition 2", type: "select", options: CHOICES.MOBILE_EXTENT },
          { name: "acquisition_program_3", label: "Program 3", type: "select", options: CHOICES.MOBILE_ACQ_PROGRAM },
          { name: "extent_of_acquisition_3", label: "Extent of Acquisition 3", type: "select", options: CHOICES.MOBILE_EXTENT },
          { name: "other_1", label: "Other", type: "text" },
          { name: "other_2", label: "Other", type: "text" },
        ],
      },
      {
        title: "Safe Copy (fill in later if not yet known)",
        fields: [
          { name: "safe_copy_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "safe_copy_start_time", label: "Start Time", type: "time" },
          { name: "safe_copy_end_date", label: "Acquisition End Date", type: "date" },
          { name: "safe_copy_end_time", label: "End Time", type: "time" },
          { name: "safe_copy_md5_hash", label: "MD5 Hash", type: "text" },
          { name: "safe_copy_sha256_hash", label: "SHA1 Hash", type: "text" },
        ],
      },
      {
        title: "Destination (Forensic) Disk",
        fields: [
          { name: "destination_type", label: "Type", type: "select", options: CHOICES.DESTINATION_TYPE },
          { name: "destination_manufacturer", label: "Manufacturer", type: "text" },
          { name: "destination_size", label: "Size", type: "text", hint: "GB/TB" },
          { name: "destination_model_name_nr", label: "Model Name/Nr", type: "text" },
          { name: "destination_serial_nr", label: "Serial Nr", type: "text" },
        ],
      },
      {
        title: "Extraction 1 (fill in later if not yet known)",
        fields: [
          { name: "extraction1_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "extraction1_start_time", label: "Start Time", type: "time" },
          { name: "extraction1_end_date", label: "Acquisition End Date", type: "date" },
          { name: "extraction1_end_time", label: "End Time", type: "time" },
          { name: "extraction1_md5_hash", label: "MD5 Hash", type: "text" },
          { name: "extraction1_sha256_hash", label: "SHA1 Hash", type: "text" },
        ],
      },
      {
        title: "Extraction 2 (fill in later if not yet known)",
        fields: [
          { name: "extraction2_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "extraction2_start_time", label: "Start Time", type: "time" },
          { name: "extraction2_end_date", label: "Acquisition End Date", type: "date" },
          { name: "extraction2_end_time", label: "End Time", type: "time" },
          { name: "extraction2_md5_hash", label: "MD5 Hash", type: "text" },
          { name: "extraction2_sha256_hash", label: "SHA1 Hash", type: "text" },
        ],
      },
      {
        title: "Extraction 3 (fill in later if not yet known)",
        fields: [
          { name: "extraction3_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "extraction3_start_time", label: "Start Time", type: "time" },
          { name: "extraction3_end_date", label: "Acquisition End Date", type: "date" },
          { name: "extraction3_end_time", label: "End Time", type: "time" },
          { name: "extraction3_md5_hash", label: "MD5 Hash", type: "text" },
          { name: "extraction3_sha256_hash", label: "SHA1 Hash", type: "text" },
        ],
      },
      {
        title: "SIM Card",
        fields: [
          { name: "sim_card_extraction", label: "SIM Data Extracted", type: "select", options: CHOICES.SIM_CARD_EXTRACTION },
          { name: "sim_notes", label: "Notes", type: "text" },
          { name: "sim_hash", label: "SIM Hash", type: "text" },
        ],
      },
      {
        title: "Memory Card",
        fields: [
          { name: "memory_card_manufacturer", label: "Manufacturer", type: "text" },
          { name: "memory_card_size", label: "Size", type: "text" },
          { name: "memory_card_serial_nr", label: "Serial Nr", type: "text" },
          { name: "memory_card_type", label: "Type", type: "select", options: CHOICES.MEMORY_CARD_TYPE },
          { name: "memory_card_other_specify", label: "Other Specify", type: "text" },
          { name: "memory_card_acquisition_program", label: "Program Used for Acquisition", type: "select", options: CHOICES.MEMORY_CARD_ACQ_PROGRAM },
          { name: "memory_card_other", label: "Other", type: "text" },
          { name: "memory_card_acq_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "memory_card_acq_start_time", label: "Start Time", type: "time" },
          { name: "memory_card_acq_end_date", label: "Acquisition End Date", type: "date" },
          { name: "memory_card_acq_end_time", label: "End Time", type: "time" },
          { name: "memory_card_md5_hash", label: "MD5 Hash", type: "text" },
          { name: "memory_card_sha1_hash", label: "SHA1 Hash", type: "text" },
        ],
      },
      { title: "Verification", fields: VERIFICATION_FIELDS },
      { title: "Additional Scene Notes", fields: NOTES_FIELD },
    ],
  },

  storage_media: {
    label: "Storage Media",
    evidenceHint: "e.g. DFL139_XOLANI_DHLAMINI_USB1",
    sections: [
      {
        title: "Device Details",
        fields: [
          { name: "type_of_devices_disks", label: "Type of Device(s) / Disk(s)", type: "text" },
          { name: "manufacturer", label: "Manufacturer", type: "text" },
          { name: "model_no", label: "Model Nr", type: "text" },
          { name: "size", label: "Size", type: "text", hint: "GB/TB" },
          { name: "visible_sn", label: "Visible SN", type: "text" },
          { name: "software_sn", label: "Software SN", type: "text" },
        ],
      },
      {
        title: "Target (Forensic) Disks",
        fields: [
          { name: "target1_type", label: "Target 1 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "target1_manufacturer", label: "Target 1 Manufacturer", type: "text" },
          { name: "target1_size", label: "Target 1 Size", type: "text", hint: "GB/TB" },
          { name: "target1_model", label: "Target 1 Model Nr", type: "text" },
          { name: "target1_serial", label: "Target 1 Serial Nr", type: "text" },
          { name: "target2_type", label: "Target 2 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "target2_manufacturer", label: "Target 2 Manufacturer", type: "text" },
          { name: "target2_size", label: "Target 2 Size", type: "text", hint: "GB/TB" },
          { name: "target2_model", label: "Target 2 Model Nr", type: "text" },
          { name: "target2_serial", label: "Target 2 Serial Nr", type: "text" },
        ],
      },
      {
        title: "Acquisition Information (fill in later if not yet known)",
        fields: [
          { name: "source_device_description", label: "Source Device Description", type: "textarea" },
          { name: "acquisition_notes", label: "Acquisition Notes", type: "textarea" },
          { name: "acquisition_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "acquisition_start_time", label: "Start Time", type: "time" },
          { name: "acquisition_end_date", label: "Acquisition End Date", type: "date" },
          { name: "acquisition_end_time", label: "End Time", type: "time" },
          { name: "extent_of_acquisition", label: "Extent of Acquisition", type: "select", options: CHOICES.EXTENT_OF_ACQUISITION_STORAGE },
          { name: "method_used", label: "Method Used", type: "select", options: CHOICES.METHOD_USED },
          { name: "md5_hash", label: "MD5 Hash", type: "text" },
          { name: "sha1_hash", label: "SHA1 Hash", type: "text" },
          { name: "notes_on_acquisition", label: "Notes on Acquisition", type: "select", options: CHOICES.NOTES_ON_ACQUISITION },
          { name: "imager_version", label: "Imager Version", type: "select", options: CHOICES.PROGRAM_OPTIONS_STORAGE },
          { name: "live_distro", label: "Live Distro", type: "select", options: CHOICES.PROGRAM_OPTIONS_STORAGE },
          { name: "other_specify", label: "Other Specify", type: "text" },
        ],
      },
      { title: "Verification", fields: VERIFICATION_FIELDS },
      { title: "Additional Scene Notes", fields: NOTES_FIELD },
    ],
  },

  email_profile: {
    label: "E-Mail/User Profile",
    evidenceHint: "e.g. DFL139_XOLANI_DHLAMINI_EMAIL1",
    sections: [
      {
        title: "Device Details",
        fields: [
          { name: "type_of_devices_disks", label: "Type of Device(s) / Disk(s)", type: "text", hint: "Server, Backup, USB, etc" },
        ],
      },
      {
        title: "Description-Details of E-Mail/User Profile",
        fields: [
          { name: "email_profile_1_name", label: "E-Mail / User Profile Name (1)", type: "text" },
          { name: "email_profile_1_md5", label: "MD5 Hash (1)", type: "text" },
          { name: "email_profile_1_sha1", label: "SHA1 Hash (1)", type: "text" },
          { name: "email_profile_2_name", label: "E-Mail / User Profile Name (2)", type: "text" },
          { name: "email_profile_2_md5", label: "MD5 Hash (2)", type: "text" },
          { name: "email_profile_2_sha1", label: "SHA1 Hash (2)", type: "text" },
        ],
      },
      {
        title: "Description-Details of Seized/Imaged Device(s)/Disks",
        fields: [
          { name: "source_type", label: "Type", type: "select", options: CHOICES.HDD_TYPE, hint: "Sata, SSD, USB, etc" },
          { name: "source_manufacturer", label: "Manufacturer", type: "text", hint: "Seagate, Sandisk, etc" },
          { name: "source_size", label: "Size", type: "text", hint: "GB/TB" },
          { name: "source_model_nr", label: "Model Nr", type: "text" },
          { name: "source_visible_sn", label: "Visible SN", type: "text" },
          { name: "source_software_sn", label: "Software SN", type: "text" },
        ],
      },
      {
        title: "Target (Forensic) Disks",
        fields: [
          { name: "target1_type", label: "Target 1 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "target1_manufacturer", label: "Target 1 Manufacturer", type: "text" },
          { name: "target1_size", label: "Target 1 Size", type: "text", hint: "GB/TB" },
          { name: "target1_model_no", label: "Target 1 Model Nr", type: "text" },
          { name: "target1_serial_no", label: "Target 1 Serial Nr", type: "text" },
          { name: "target2_type", label: "Target 2 Type", type: "select", options: CHOICES.HDD_TYPE },
          { name: "target2_manufacturer", label: "Target 2 Manufacturer", type: "text" },
          { name: "target2_size", label: "Target 2 Size", type: "text", hint: "GB/TB" },
          { name: "target2_model_no", label: "Target 2 Model Nr", type: "text" },
          { name: "target2_serial_no", label: "Target 2 Serial Nr", type: "text" },
        ],
      },
      {
        title: "Acquisition Information (fill in later if not yet known)",
        fields: [
          { name: "acquisition_start_date", label: "Acquisition Start Date", type: "date" },
          { name: "acquisition_start_time", label: "Start Time", type: "time" },
          { name: "acquisition_end_date", label: "Acquisition End Date", type: "date" },
          { name: "acquisition_end_time", label: "End Time", type: "time" },
          { name: "extent_of_acquisition", label: "Extent of Acquisition", type: "select", options: CHOICES.EXTENT_OF_ACQUISITION_STORAGE },
          { name: "method_used", label: "Method Used", type: "select", options: CHOICES.METHOD_USED },
          { name: "type_of_email_account", label: "Type of E-Mail Acc", type: "select", options: CHOICES.TYPE_OF_EMAIL_ACCOUNT },
          { name: "online_email", label: "Online E-Mail", type: "text", hint: "Yahoo, Hotmail, Gmail, Live, etc" },
          { name: "md5_hash", label: "MD5 Hash", type: "text" },
          { name: "sha1_hash", label: "SHA1 Hash", type: "text" },
          { name: "notes_on_acquisition", label: "Notes on Acquisition", type: "select", options: CHOICES.NOTES_ON_ACQUISITION },
          { name: "imager_version", label: "Imager Version", type: "select", options: CHOICES.PROGRAM_OPTIONS_STORAGE },
          { name: "other_specify", label: "Other Specify", type: "text" },
        ],
      },
      { title: "Verification", fields: VERIFICATION_FIELDS },
      { title: "Additional Scene Notes", fields: NOTES_FIELD },
    ],
  },
};
